include_guard(GLOBAL)

macro(enable_project_coverage)
    if(COVERAGE)
        if(APPLE AND CMAKE_CXX_COMPILER_ID MATCHES "AppleClang|Clang")
            include(LLVMCodeCoverage)
            append_llvm_coverage_compiler_flags()
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
            include(GCCCodeCoverage)
            append_gcc_coverage_compiler_flags()
        else()
            message(FATAL_ERROR
                "Coverage is supported only with GCC or macOS AppleClang/Clang.")
        endif()
    endif()
endmacro()
